### ISSUE TITLE
Remove IIFE Before Adding

### ISSUE THREAD

**Issue by trisys3** [mariusschulz/gulp-iife#12]
Is there any way to programmatically detect that there is already an IIFE? Our codebase already uses IIFEs, but I am thinking about using gulp-iife instead. I am worried about the performance implications of using 2 IIFEs, though I haven't done any performance tests. It's a big codebase, so I have to think there would be at least some performance loss, though this may be dwarfed by our use of angular, among other things.

One of our applications already uses gulp-iife, and it seems to work fine. The only issue is that we do not concatenate with gulp-iife in development, meaning things like an accidental global `this` causes problems in production but not development, but that is on us. Anyway, great job!

If there is no (easy) way to programmatically detect that there is an IIFE, or if you have to use `acorn` or something like that, please ignore and close this issue. If there is a way, could you look into supporting this? I would be fine with it being an optional option.

**Comment by fvictorio** [comment]
I can't speak for Marius, but I think using `acorn` (or some equivalent tool) is the only reasonable option. Using regex for this sounds problematic.

I've actually been looking for an excuse to play with JS ASTs, and this seems like an easy but useful use case. @mariusschulz, would you be willing to accept a PR for this?

**Comment by mariusschulz** [comment]
I agree that regular expressions aren't the tool of choice here, but I'd be happy to accept a PR if you can come up with a clean AST solution!

**Comment by trisys3** [comment]
Thanks, I didn't expect you guys to answer so quickly. I have never looked at ASTs or acorn, so I'll just sit on the sidelines & cheer you on.

**Comment by fvictorio** [comment]
@trisys3, can you take a look at the discussion in #13 and give us an opinion on what would you find more useful?

**Comment by trisys3** [comment]
I just added a long note to that discussion. Basically, anything is fine, we don't have params/args as we use `window` for globals. We use 'use strict', so that could still be an issue. `babel-polyfill` "helpfully" adds it to the top scope for us, though, so everything is strict, at least for now, so it doesn't matter.

**Comment by trisys3** [comment]
About the `babel-polyfill` thing, I just recently found out about that, which shows how little 'use strict' matters for us. I could add `gulp-iife` around everything, just haven't gotten around to it.

**Comment by chiragparmar17** [comment]
Please merge the pull request #13. I need it urgently.

**Comment by trisys3** [comment]
@Maruis, I guess this issue should be closed if you're not going to work on it, to avoid confusing people, unless you wanted to encourage pull requests?
