### ISSUE TITLE
Publish lodash fix to NPM

### ISSUE THREAD

**Issue by mariovalney** [mariusschulz/gulp-iife#15]
Hey! How are you?

I came to to try to contribute into updating lodash version and I checked out you already did it.
Would you mind to publish this new version? 

I runned the tests and everything sound ok. Is something needed? I Please, let me know If I can help somehow.

Thanks for your work.

**Comment by mariusschulz** [comment]
Hey Mário, I just published v0.4.0 — let me know if anything isn't working for you!
