### ISSUE TITLE
Apply it only to part of the sources?

### ISSUE THREAD

**Issue by alvarotrigo** [mariusschulz/gulp-iife#16]
I'm using a gulp task to combine and minify js files.
Some of those files belong to vendor libraries. Others are my own code.

I only want to add the iife to my won code. How can I do this without having to generate two temporal files that I combine later on?

**Comment by mariusschulz** [comment]
I'm afraid _gulp-iife_ doesn't currently support this use case. I'd be happy to review a PR though!
