### ISSUE TITLE
Exporting global names improvement

### ISSUE THREAD

**Issue by edwardcoolson** [mariusschulz/gulp-iife#2]
Hi Marius, I'd like to suggest you one new feature for your plugin. Sometimes it is needed to have one or more names (variables or functions) from the original code to be exported as globals. For example:

    var a = 'some private stuff';
    var b = 'some other private stuff';

    // this is my object I would like to be globally accessible after wrapping into IIFE
    function MyObject(params)
    {
      // here I'm using a, b and other private members
      ...    
    }

I would want this code after processing:

    (function(context, globals) {
      var a = 'some private stuff';
      var b = 'some other private stuff';

      // this is my object I would like to be globally accessible after wrapping into IIFE
      function MyObject(params)
      {
        // here I'm using a, b and other private members
        ...    
      }

      // section to export global names
      for(var i = 0; i < globals.length; i++)
        context[globals[i]] = eval(globals[i]);

    })(window, ['MyObject']);

where context and globals are both specified in plugin's config. context is global namespace usually window, globals is just an array of existing var/function names we want to be accessible at global level. eval is used to specify var/function by string name inside IIFE (it seems like this is the only way to access local name inside IIFE). 

What do you think?

**Comment by mariusschulz** [comment]
Hi Edward,

While I can see the use case in your specific example, I don't think exporting variables or functions should be a responsibility of *gulp-iife*. I'd like to keep the plugin as simple as possible and focused on the one thing it should do: adding IIFE wrappers.

Frankly, I'm also not a huge fan of injecting `eval` statements as they open up the code for a plethora of vulnerabilities and security holes.

Marius
