### ISSUE TITLE
enhancement request: sourcemap support

### ISSUE THREAD

**Issue by mattsawyer77** [mariusschulz/gulp-iife#8]
It would be awesome if this plugin supported sourcemaps (a la https://github.com/floridoo/gulp-sourcemaps). I've tried to use them with an intermediary iife pipe operation but then my breakpoints seem to be thrown off in the browser's developer tools.

Here is some documentation: https://github.com/floridoo/gulp-sourcemaps#plugin-developers-only-how-to-add-source-map-support-to-plugins

**Comment by mariusschulz** [comment]
I'm not sure I understand why your breakpoints were thrown off. If you run `gulp-iife` before other transformations that create source maps (such as minification using [UglifyJS](https://github.com/mishoo/UglifyJS2), for example), those later transformations should respect the added lines. Could you please elaborate on this a little more?

**Comment by BlaMaeda** [comment]
Hello Marius.

I made an example showing the issue that Matt has: https://github.com/BlaMaeda/iife-sourcemaps

Clone the repo, `npm install && gulp build` and open the `index.html` file (with an http server, of course) and look at the console output.

Cheers.

**Comment by mattsawyer77** [comment]
I've since found that putting ```iife()``` before ```sourcemaps.init()``` seems to fix my problem (I can tolerate each file having its own iife wrapping).

**Comment by mariusschulz** [comment]
@mattsawyer77 Have you tried updating gulp-iife to the newest version? In the meantime, we've added support for source maps. Does your problem still persist?

**Comment by mattsawyer77** [comment]
I'll attempt that sometime soon and report back. Sorry for the slow feedback -- I've only been able to spend a small amount of time on this here and there.

**Comment by mattsawyer77** [comment]
Seems to be all good now. Thank you.
